name: 'Create TOC'

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

description: 'Create an HTML Table of Contents file for a project'
inputs:
  branch:
    description: "The branch to process (default: gh-pages)"
    required: false
    default: "gh-pages"
  github-token:
    description: "The GitHub token"
    required: true
    default: "of course it fails"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
